### ISSUE TITLE
FWTS patch application failure while building BBR FWTS

### ISSUE THREAD

**Issue by edhay** [ARM-software/bbr-acs#73] opened 2024-06-05 04:10 UTC
Patch application failure warnings when building FWTS through build_sbbr.sh

HEAD is now at f09402bb lib: fwts_version.h - update to V23.01.00
~/BBR-BUILD/bbr-acs/sbbr/scripts
edhcha01@a074700:~/BBR-BUILD/bbr-acs/sbbr/scripts$ ./build-scripts/build_sbbr.sh
~/BBR-BUILD/bbr-acs/sbbr/scripts ~/BBR-BUILD/bbr-acs/sbbr/scripts
~/BBR-BUILD/bbr-acs/sbbr/scripts
~/BBR-BUILD/bbr-acs/sbbr/scripts/fwts ~/BBR-BUILD/bbr-acs/sbbr/scripts
~/BBR-BUILD/bbr-acs/sbbr/scripts
~/BBR-BUILD/bbr-acs/sbbr/scripts/fwts ~/BBR-BUILD/bbr-acs/sbbr/scripts
/home/edhcha01/BBR-BUILD/bbr-acs/sbbr/scripts/../..
2 out of 2 hunks FAILED
Applying FWTS Patch ...
patching file src/lib/src/fwts_framework.c
1 out of 1 hunk FAILED
1 out of 1 hunk FAILED

The same issue may exist in build_ebbr.sh too.
Also please check if the same issue exists when building FWTS in SystemReady ACS.

**Comment by sunnywang-arm** [comment] 2024-06-06 16:19
I can reproduce this issue with WSL on a x86 system

```
sunny@xxxxx: /mnt/c/src/bbr-acs/sbbr/scripts$ ./build-scripts/build_sbbr.sh
/mnt/c/src/bbr-acs/sbbr/scripts /mnt/c/src/bbr-acs/sbbr/scripts
/mnt/c/src/bbr-acs/sbbr/scripts
/mnt/c/src/bbr-acs/sbbr/scripts/fwts /mnt/c/src/bbr-acs/sbbr/scripts
/mnt/c/src/bbr-acs/sbbr/scripts
/mnt/c/src/bbr-acs/sbbr/scripts/fwts /mnt/c/src/bbr-acs/sbbr/scripts
/mnt/c/src/bbr-acs/sbbr/scripts/../..
2 out of 2 hunks FAILED
Applying FWTS Patch ...
patching file src/lib/src/fwts_framework.c
1 out of 1 hunk FAILED
1 out of 1 hunk FAILED
Applying FWTS build patch ...
patching file src/lib/include/fwts_fileio.h
patching file src/lib/src/fwts_fileio.c
./build-scripts/build-fwts.sh: line 111: autoreconf: command not found

Build failed: error while running do_build at line 111 in ./build-scripts/build-fwts.sh for [][].
```

**Comment by chetan-rathore** [comment] 2024-06-18 04:01
Hello @sunnywang-arm,

Can you please check with latest bbr-acs code if the SBBR/EBBR working fine on WSL environment, the issue seems to be due to autoconf tool dependency not met in build enviroment.


Thanks,
Chetan

**Comment by sunnywang-arm** [comment] 2024-06-18 21:36
@chetan-rathore it somehow doesn't work and I still need to manually install the the autoconf.  After installing autoconf, I ran into another build error 
```
root@PF4Q726R:/mnt/c/src/bbr-acs/sbbr/scripts# ./build-scripts/build_sbbr.sh
ln: failed to create symbolic link '/mnt/c/src/bbr-acs/sbbr/scripts/build-scripts/framework.sh': File exists
ln: failed to create symbolic link '/mnt/c/src/bbr-acs/sbbr/scripts/build-scripts/parse_params.sh': File exists
ln: failed to create symbolic link '/mnt/c/src/bbr-acs/sbbr/scripts/build-scripts/build-sct.sh': File exists
ln: failed to create symbolic link '/mnt/c/src/bbr-acs/sbbr/scripts/build-scripts/build-uefi-apps.sh': File exists
ln: failed to create symbolic link '/mnt/c/src/bbr-acs/sbbr/scripts/build-scripts/build-fwts.sh': File exists
/mnt/c/src/bbr-acs/sbbr/scripts /mnt/c/src/bbr-acs/sbbr/scripts
/mnt/c/src/bbr-acs/sbbr/scripts
/mnt/c/src/bbr-acs/sbbr/scripts/fwts /mnt/c/src/bbr-acs/sbbr/scripts
/mnt/c/src/bbr-acs/sbbr/scripts
/mnt/c/src/bbr-acs/sbbr/scripts/fwts /mnt/c/src/bbr-acs/sbbr/scripts
/mnt/c/src/bbr-acs/sbbr/scripts/../..
autoreconf: export WARNINGS=
autoreconf: Entering directory '.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
aclocal: warning: couldn't open directory 'm4': No such file or directory
autoreconf: configure.ac: tracing
autoreconf: configure.ac: not using Libtool
autoreconf: configure.ac: not using Intltool
autoreconf: configure.ac: not using Gtkdoc
autoreconf: running: /usr/bin/autoconf --force
configure.ac:7: warning: AC_PROG_LEX without either yywrap or noyywrap is obsolete
./lib/autoconf/programs.m4:716: _AC_PROG_LEX is expanded from...
./lib/autoconf/programs.m4:709: AC_PROG_LEX is expanded from...
configure.ac:7: the top level
configure.ac:9: error: possibly undefined macro: AC_PROG_LIBTOOL
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: error: /usr/bin/autoconf failed with exit status: 1

Build failed: error while running do_build at line 111 in ./build-scripts/build-fwts.sh for [][].
```

**Comment by chetan-rathore** [comment] 2024-06-19 17:05
Hi @sunnywang-arm,

It could be due to some missing dependencies in WSL system.
Can you provide information on OS and its version installed as part of WSL system.

Thanks,
ACS team

**Comment by sunnywang-arm** [comment] 2024-06-20 15:25
```
sunny@PF4Q726R:~$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

**Comment by sunnywang-arm** [comment] 2024-07-15 22:25
Thanks, @chetan-rathore 

I'm fine with closing the issue now as it works on my WSL after I re-do everything (clone the bbr-acs source code and re-run all the commands mentioned in readme again). 

@edhay  do you want to give the latest bbr-acs a try on your side?

**Comment by chetan-rathore** [comment] 2024-09-10 03:14
Thanks @sunnywang-arm for the confirmation.

@edhay Please let us know if bbr acs build works at your side also and the ticket can be closed.

**Comment by edhay** [comment] 2024-09-10 21:25
Hi @chetan-rathore ,

   Tried the build on the latest code. I am still getting the same error:
![Screenshot 2024-09-10 162521](https://github.com/user-attachments/assets/cf6351a9-b957-4676-a54c-d2a9471683f1)

**Comment by chetan-rathore** [comment] 2024-09-11 04:29
Hi @edhay,

Can you share the OS version details of the machine on which you are building.
It more seems to be system dependency issue rather than bbr-acs.
The daily scheduled builds are working fine: https://github.com/ARM-software/bbr-acs/actions

Thanks,
ACS team

**Comment by edhay** [comment] 2024-09-11 18:49
Details shared by email.

**Comment by chetan-rathore** [comment] 2024-11-17 11:17
Hi @edhay,

The error on the terminal is due to patch command -R (reverse)  failure when applied to file where patch is already not applied.
https://github.com/ARM-software/bbr-acs/blob/main/common/scripts/build-fwts.sh#L90
The logic checks if "patch is not applied" then apply the patch...else if patch already applied then skip applying patch and proceed.

Thanks,
Chetan

**Comment by chetan-rathore** [comment] 2024-12-02 05:52
Hi @edhay,

With latest changes as mentioned above, no patch reverse failure prints should be coming.
Please reopen if you have any further queries.

Thanks,
Chetan

**Closed by chetan-rathore** 2024-12-02 05:52 UTC
Labels: bug
